### ISSUE TITLE
Azure load balancers don't work with comma separated port lists

### ISSUE THREAD

**Issue by alexjh** [colstrom/cloudstrap-azure#3]
https://github.com/Azure/ACS/issues/114

Making an NSG with a destination port range of `80,443,`... doesn't work with the Azure load balancer.

According to the ACS bug mentioned above, this doesn't work with Kube 1.7 or older, and I *think* that's the only version available.

I've been able to proceed by manually creating individual rules for each port.

**Comment by colstrom** [comment]
Fixed in `0.7.0.pre`.
