### ISSUE TITLE
Is it supposed to run on Mac?

### ISSUE THREAD

**Issue by axelaris** [colstrom/cloudstrap-azure#5]
```
$ cloudstrap-azure environment
/Library/Ruby/Gems/2.0.0/gems/cloudstrap-azure-0.7.1.pre/command/internal/cloudstrap-azure.environment:85:in `<main>': undefined method `to_h' for #<Array:0x007fcce22287b8> (NoMethodError)

$ ruby -v
ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
```

**Comment by colstrom** [comment]
Yep, sure is. The majority of the development happens on a Mac!

That said, Ruby 2.0.0 reached End of Life on 2016-02-24. If you're on macOS 10.12, `2.0.x` is the included version. If you're on macOS 10.13, you should have `2.3.x`, which is still supported.

I'd recommend using a stable release via [Homebrew](https://brew.sh/) (or your package manager of choice):

```shell
brew install ruby
```

Hope that helps!

**Comment by axelaris** [comment]
Thank you, @colstrom, it helps!
It would be honest to note Ruby version in Prerequisites.

**Comment by colstrom** [comment]
Thanks, that's a good idea.
